repos:
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.9.3
    hooks:
      - id: isort
        args: ["--profile=black"]

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
  
  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
        name: Run Black formatter
        language_version: python3.9
        args: ["--line-length=88"]
