[tool.isort]
profile = "black"
known_third_party = ["pyspark", "dotenv"]
known_local_folder = ["scripts"]
line_length = 88

[tool.black]
line-length = 88
target-version = ["py38"]
skip-string-normalization = false
