name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    #services:
    #  docker:
    #    image: docker:latest
    #    options: --privileged

    steps:
      # Checkout do repositório
      - name: Checkout the repository
        uses: actions/checkout@v2

      # Configuração do Python
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      # Instalar dependências do projeto
      - name: Install Python dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      # Rodar testes de unidade
      - name: Run Unit Tests
        run: |
          source venv/bin/activate
          python -m unittest discover -s tests
